import {
  AlertTriangle,
  ArrowRight,
  Book,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Folder,
  HelpCircle,
  Image as Photo,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  ShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Sun,
  Trash2,
  User,
  UserCheck,
  UserCircle,
  UserPen,
  Users,
  UserX,
  X,
  Kanban,
  type LucideProps,
} from "lucide-react";

export type Icon = React.ComponentType<LucideProps>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: ShoppingBag,
  spinner: Loader2,
  kanban: Kanban,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash2,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle,
  media: Photo,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  book: Book,
  folder: Folder,
  users: Users,
  "user-check": UserCheck,
};
